### ISSUE TITLE
smb.conf for zfsnap

### ISSUE THREAD

**Issue by tonyblue2** [zfsnap/zfsnap#103]
I want to access the snapshots of zfsnap per samba 

Whats the right entry in smb.conf? This doesn´t work for me:

    vfs objects = shadow_copy2
    shadow: snapdir = .zfs/snapshot
    shadow: sort = desc
    shadow: format = %Y-%m-%d_%H.%M.%S--5d
    shadow:localtime = no

What´s wrong?

Thank you!

Tony

**Comment by graudeejs** [comment]
This is not zfSnap issue
