### ISSUE TITLE
Request: Add support for a pre- and post-script

### ISSUE THREAD

**Issue by wolph** [zfsnap/zfsnap#105]
For some goals such as Postgres database backups it's needed to run a command (`pg_start_backup(label)`)before you take the snapshot. While the snapshot will probably work just fine without it, running this command before making the snapshot makes sure everything will work effortlessly while restoring.

So having the option to add a `pg_start_backup()` before snapshotting and a `pg_stop_backup()` after would be very helpful :)

**Comment by graudeejs** [comment]
Doesn't && work for you?
```
pre.sh && zfsnap ... && post.sh
```

**Comment by WoLpH** [comment]
Yes, but for clarity sake it would be nice to integrate it with the periodic script.

I know I can do it in the cron definition as well but that just seems wrong too

**Comment by rawtaz** [comment]
I would argue that this is out of scope for the core of this software. The use case can be met by regular usage of the system and its shell, so it'd be better to not make the source code more complex, especially when there's not even an active maintenance of this software. I suggest closing this issue, with all due respect to the author of it and their use case of course.

**Comment by ppreeper** [comment]
This is outside scope of the software.
