### ISSUE TITLE
Make prefixes not need - at the end

### ISSUE THREAD

**Issue by rawtaz** [zfsnap/zfsnap#113]
Currently with 2.0.0-beta3 when using the -p option to specify a "foo" prefix, e.g. `-p foo`, zfsnap creates a snapshot named like `tank/mine@foo2020-10-11_12.50.00--1m`.

I would have expected the snapshot name when using the prefix "foo" to be `tank/mine@foo-2020-10-11_12.50.00--1m`, and I fail to see the use of having to specify the prefix as "foo-" in order to have a properly separated-from-date prefix in the snapshot name.

Now that we have a major version change, can't we just make zfsnap automatically separate prefixes with "-" from the date, so one don't have to suffix prefixes with "-" to get proper snapshot names? It's the best and practically only opportunity we'll have in a very long time.

**Comment by graudeejs** [comment]
zfsnap is unmaintained.

**Comment by rawtaz** [comment]
> zfsnap is unmaintained.

This does not mean that the current (inactive if you wish) maintainer and/or others can have their say on matters like this, and when/if there's ever going to be a 2.0.0 *release*, this issue is still valid for consideration as part of that process. I wanted to raise this suggestion before 2.0.0 is released, for starters.

**Comment by rawtaz** [comment]
FWIW, it might be prudent to implement this such that if a given prefix ends with a `-`, zfsnap trims it off before adding its own automatically, so that there's only one `-` separating prefix and date. This need proper documenting but would mean that we keep BC.
