### ISSUE TITLE
Minor error in manpage

### ISSUE THREAD

**Issue by edwinsage** [zfsnap/zfsnap#115]
In the manpage, there's an example that says "Every hour, create recursive snapshots of an entire pool and keep for 5 days.", but the actual example would create a snapshot every 5 minutes.
https://github.com/zfsnap/zfsnap/blob/2d590e2c828638d6235b033415c6fa05a5202996/man/man8/zfsnap.8#L276C1-L276C78

**Comment by ppreeper** [comment]
Hi there, the man page shows:
```
Every hour, create recursive snapshots of an entire pool and keep for 5 days.
# Minute  Hour  Day  Month  Day  Who   Command
5         *     *    *      *    root  /sbin/zfsnap snapshot \-a 5d \-r zpool
```

It states that it would create it every hour. This is correct in `crontab` entry. The first character being a 5 tell the cron system to execute this at the 5 minute mark of any (*) hour on any (*) day of the month on any(*) month and any(*) day of the week.
At first glance it looks like every five minutes, but it is actually executing at the 5 minute mark (ex. 00:05, 01:05, 13:05 ...).
To execute every five minutes the first field would have to be `*/5`

I hope this explains the issue.

**Comment by edwinsage** [comment]
Haha, my cron is rusty, it seems.  Thanks for the explanation!

**Comment by graudeejs** [comment]
Perhaps minor man page enhancement can be made. Instead of `5 * * * *` change it to something else, say `0 * * * *` this would be more intuitive.
Just my 2 cents.

**Comment by ppreeper** [comment]
That's a very good point. We all have been bit by the crontab format at somepoint in our careers. I will update that in the man page documentation to make it clear.
