### ISSUE TITLE
Fails to destroy snapshot if it was cloned

### ISSUE THREAD

**Issue by graudeejs** [zfsnap/zfsnap#14]
It seams that zfSnap can fail to destroy snapshot if it has clones.
Needs more investigation

**Comment by Alexqw** [comment]
@graudeejs I tested this and it now works as you describe. It does output an error, but I think this is desirable behavior, as errors should not be silent. If a user wants to suppress them, then they can 2> /dev/null

---Alex

**Comment by graudeejs** [comment]
Excelent
