### ISSUE TITLE
Request: Option to send snapshots to alternative pool

### ISSUE THREAD

**Issue by comm** [zfsnap/zfsnap#2]
Hi,

Firstly, thank you for creating this script, its been really useful.

I have decided to create a second pool to fully backup a filesystem on my main pool and was wondering if you could add an option (-b?) to backup the snapshot to an alternative pool. e.g. `zfSnap -a 5d -r zpool -b bpool`

This would first check if the current filesystem in the loop (e.g. xyz) exists in the bpool. If it doesn't then it will just `zfs send zpool/xyz | zfs recv bpool/xyz`. If it does exist then the script will get the n (just created) snapshot and the n-1 snapshot and send an incremental backup  `zfs send -i zpool/xyz@n zpool/xyz@n-1 | zfs recv bpool/xyz`

Is this achievable?

Thanks,

Comm

**Comment by Alexqw** [comment]
@comm Thanks fir the suggestion. :-) I do have plans to implement this, but it won't be for the 2.0 release. Probably 2.1. I'm closing this issue, as I'll track any changes in issue #48.

---Alex
