### ISSUE TITLE
FATAL: trying to delete zfs pool or filesystem? WTF?

### ISSUE THREAD

**Issue by rcsheets** [zfsnap/zfsnap#28]
Saw this in my weekly run output, so opening an issue as directed.

    /sbin/zfs snapshot -r pool0/home@weekly-2014-02-22_04.44.26--1m ... DONE
    /sbin/zfs snapshot -r zroot@weekly-2014-02-22_04.44.26--1m ... DONE
    NOTE: No action will be performed on 'pool0@daily-2014-02-14_04.15.58--1w'. Scrub is running on pool.
    NOTE: No action will be performed on 'pool0@daily-2014-02-15_04.02.02--1w'. Scrub is running on pool.
    FATAL: trying to delete zfs pool or filesystem? WTF?
      This is bug, we definitely don't want that.
      Please report it to https://github.com/graudeejs/zfSnap/issues
      Don't panic, nothing was deleted :)

I'm not really sure what went wrong, or what additional information I should provide, so please let me know how I can help.

**Comment by Alexqw** [comment]
Closing, as this seems to be resolved in the 2.x codebase.

---Alex
