### ISSUE TITLE
ver2.0.0 solaris 11

### ISSUE THREAD

**Issue by larmar** [zfsnap/zfsnap#53]
I get error with local variables in bourne shell. It seems not supported in bourne shell ?
I also got error in Exit 0, share/commands/snapshot.sh and destroy.sh.
The capital E creates an error exit 0 works good.

**Comment by Alexqw** [comment]
@larmar I'm now regularly running automated testing on Solaris 11. Indeed, Solaris's sh doesn't support local, nor does its version of ksh (ksh93), but you're right that bash does indeed work.

I wrote a script to fix the shebang's for systems without a /bin/sh that supports "local." If you download the most recent code, the following should change all of zfsnap to bash:

    find ./ -type d \( -name tools -o -name vagrant \) -prune -o -type f -exec tools/mod_shebang.sh -s '#!/bin/bash' {} \;

I was unable to reproduce your problem with Exit, but if you still have a problem with it, please reopen this issue.

---Alex
