### ISSUE TITLE
Feature to "promote" existing snapshots instead of creating new ones?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [zfsnap/zfsnap#71]
I'm setting up a ZFS-based backup server for my home, and my ideal scenario is that all the other machines will sync their important data to the backup server every hour, and then zfsnap will keep shapshots of all that data. However, if I set up separate cron jobs for the sync and the snapshotting, there's no guarantee that some snapshots won't happen in the middle of a sync. I could solve this problem for the hourly snapshots by putting the zfsnap command and sync commands in the same file. However, the daily, weekly, etc. snapshots, must be in separate scripts, so that wouldn't solve the problem. Ideally, I would like to be able to "promote" snapshots from one prefix to another. For example, the daily snapshot script would find the latest snapshot with a prefix of "hourly-" that is at least 24 hours old and rename it to have the "daily-" prefix instead, also changing the TTL at the same time. Similarly, the weekly script would promote a 7-day-old daily snapshot to a weekly. With this scheme, snapshots are only ever created in one place (the hourly script), so there is no chance of daily/weekly/etc. snapshots happening in the middle of a sync. 

An alternative solution to the problem would be to have an option to only create a snapshot if no existing snapshot with the same prefix is younger than a certain age. For example, "create a daily snapshot only if there is no currently existing daily snapshot is less than 23 hours old". Then I could put all the snapshot creation commands in the hourly script after the sync commands, so they would all never happen during a sync.

Would there be any interest in implementing either feature?

**Comment by DarwinAwardWinner** [comment]
After having a look at the codebase, I think I could probably try my hand at implementing either feature.

**Comment by Alexqw** [comment]
Closing, as I agree that #73 is a much better solution.

---Alex
