### ISSUE TITLE
Installation on Mac problems

### ISSUE THREAD

**Issue by wiegraffolles** [zfsnap/zfsnap#76]
I ran the tests included with the latest release and they all passed, but for some reason when I try to actually use zfsnap with this command:

`./zfsnap.sh snapshot -rv -a 6w zfspartition/Home`

I get the following error:

```
/../share/zfsnap/core.sh: line 190: /usr/sbin/zfs: No such file or directory
FATAL: 'zfspartition/Home' does not exist!
```
If I run zfs mount I get the following output
```

zfspartition                    /Volumes/zfspartition
zfspartition/Home               /Volumes/zfspartition/Home
zfspartition/VideoFiles         /Volumes/zfspartition/VideoFiles
```
So I think it should work, especially with all the tests passing...I've tried running the script as the super user and tried using sh, bash, and fish, and I always get the same results. Any suggestions on what to do would be much appreciated.

**Comment by neuhalje** [comment]
What does `which zfs` say?  `core.sh` tries to run `/usr/sbin/zfs`, maybe your `zfs` executable is somewhere else.

**Comment by wiegraffolles** [comment]
`which zfs` reports that the executable is at `/usr/local/bin/zfs`. I installed OpenZFS on OSX from the official .dmg file, so I can say that this is the default install location on Mac. Do you have any suggestions on how to fix the script?

**Comment by Alexqw** [comment]
@wiegraffolles You need to edit  zfsnap/share/zfsnap/core.sh, scroll to the very end where it says "Darwin" and change the two lines to the correct locations on your system.

    ZFS_CMD='/usr/sbin/zfs'
    ZPOOL_CMD='/usr/sbin/zpool'

However, you said you installed this from the official dmg? If `/usr/local/bin/` is the typical location of zfs commands on OSX, then this default needs to be changed.

If there are any other OS X users out there, please chime in. Otherwise, I will most likely change the default location on OS X.

---Alex

**Comment by wiegraffolles** [comment]
@Alexqw Yes I downloaded the 1.4.5 release from this page and used it to install OpenZFS:

https://openzfsonosx.org/wiki/Downloads

I will try editing core.sh now and see what results I get.

**Comment by wiegraffolles** [comment]
Changing core.sh as follows got the script working for me:

```
ZFS_CMD='/usr/local/bin/zfs'
ZPOOL_CMD='/usr/local/bin/zpool'
```

Thanks so much for your help!

**Comment by Alexqw** [comment]
@wiegraffolles Fixed in the latest. Thanks for the bug report!
