### ISSUE TITLE
Date2Timestamp test fails... 25200 seconds (7hrs) off?

### ISSUE THREAD

**Issue by tHubig** [zfsnap/zfsnap#78]
```
./run.sh 

`Date2Timestamp '2014-01-29_02.03.00'` echos `1390953780` ... failed
  expected result: 1390953780
    actual result: 1390978980

`Date2Timestamp '2013-12-28_22.13.01'` echos `1388261581` ... failed
  expected result: 1388261581
    actual result: 1388286781
```

I think there is something different about date or sed on Arch linux. I just switched from Ubuntu where all the tests passed.

**Comment by Alexqw** [comment]
@tHubig You're running an old beta of zfsnap, and Date2Timestamp no longer even exists in the current version. I highly recommend updating. :-)

---Alex

**Comment by tHubig** [comment]
I did eventually decide use to the master branch, which works fine... it's just that the docs sort of give the impression that the "legacy" branch is safer so I tried it first.

**Comment by Alexqw** [comment]
@tHubig Ahh, yeah. I should update those. Not to mention finally cut a release.

Glad to hear it works now. Closing. :-)

---Alex
