### ISSUE TITLE
Tag next release (2.0.0.beta3?)

### ISSUE THREAD

**Issue by mmatuska** [zfsnap/zfsnap#80]
Hi, I would be great to tag 2.0.0.beta3 (or something higher if desired), there have been important changes since 2.0.0.beta2

**Comment by aqw** [comment]
@mmatuska You're completely right. It's the least I can do. It has been tagged. :-)

Now if my boss would just stop giving me stuff to do, I could get around to finishing the last bits and make this damn 2.0 release! ;-)

---Alex
