### ISSUE TITLE
redirection to stderr prevents use in systemd-services

### ISSUE THREAD

**Issue by rabnab** [zfsnap/zfsnap#91]
redirection of stdout to stderr in lines like:

```
365: if $zfs_snapshot > /dev/stderr ; then
366: .......
```
cause creation of /dev/stderr which is not possible if it is a socket (as is the case in systemd environment).
The error message displays as follows:
```
 /usr/sbin/zfSnap: 365: /usr/sbin/zfSnap: cannot create /dev/stderr: No such device or address
Dec 31 13:45:18 HOSTNAME zfSnap[29682]: /sbin/zfs snapshot -r data@prefix2016-12-31_13.00.00--2h01s ... FAIL
```

my proposed solution is to replace every occurence of `> /dev/stderr` with ` 1>&2`.
this also works for sockets, as discussed [here](https://lists.freedesktop.org/archives/systemd-devel/2015-April/031245.html)

**Comment by graudeejs** [comment]
That breaks unix

**Comment by aqw** [comment]
@rabnab @graudeejs This is already done in zfsnap2, as it turns out /dev/stderr is (surprisingly) not POSIX nor portable....

Thanks for the bug report.

---Alex

**Comment by graudeejs** [comment]
@aqw have you got some references about that?
Would love to read

**Comment by graudeejs** [comment]
Ok, seams like you're right.

**Comment by aqw** [comment]
@graudeejs If you need me to, I can dig up the POSIX doc somewhere. But yeah, I remember both of us being surprised when it came up 2~3 years ago.

---Alex

**Comment by graudeejs** [comment]
It's fine.... quick search uncovered the horrible truth :)
