### ISSUE TITLE
Possibility to use inotify to trigger snapshots

### ISSUE THREAD

**Issue by Harvie** [zfsnap/zfsnap#99]
NILFS2 is filesystem that by design creates snapshot after any data change, so it can be easily rolled back to any time without specificaly making snapshots at that time using cron... Is it possible to mimick such feature using inotify to watch file changes and make snapshots accordingly? Maybe not for every inotify event, but at least for some.

**Comment by graudeejs** [comment]
This won't be portable, AFAIK.

**Comment by kraduk** [comment]
just use icrond to trigger zfssnap

**Comment by ppreeper** [comment]
This is outside the scope of the snapshot functionality. The inotify would be the monitor to trigger a snapshot. Since zfsnap would be the one called it is outside this software scope to add filesystem monitoring too.

**Comment by Harvie** [comment]
> The inotify would be the monitor to trigger a snapshot. Since zfsnap would be the one called

Not really. inotify is OS API that zfsnap can poll for filesystem changes.
